import { state } from '../state.js';
import { eyebrow } from '../ui/eyebrow.js';
import { primary, textButton } from '../ui/button.js';
import { productStage, dropCopy, stageTabs } from '../components/dropout-stage.js';

/* Page Dropout : introduction, scene pilotable au scroll, appel a l'action. */
export function dropout(){
  const scrollSync = state.scrollSync;
  return `<section class="drop-intro"><button class="back" data-page="home">← Nos solutions</button><div class="drop-intro-grid"><div>${eyebrow('TRAITEMENT DE L’AIR COMPRIMÉ')}<h1>Drop’out.</h1><h2>Protéger ce qui fait<br>avancer vos procédés.</h2></div><div><p>Une technologie de séparation des liquides et particules, pour préserver vos organes pneumatiques et vos instruments.</p><div class="intro-actions">${primary('Étudier mon application','data-need="Dropout — air comprimé"')}${textButton('Explorer le fonctionnement','data-scroll="fonctionnement"')}</div></div></div></section><section class="drop-experience cinematic" id="fonctionnement"><div class="drop-sticky"><div class="drop-workspace"><div class="drop-stage-shell">${productStage()}</div><div class="drop-editorial">${eyebrow('COMPRENDRE LE PRINCIPE')}<div class="drop-copy" aria-live="polite">${dropCopy()}</div>${stageTabs()}${`<button class="sync-button" aria-pressed="${scrollSync}" data-sync>Progression au scroll : ${scrollSync?'activée':'en pause'}</button>`}<p class="small-note">Choisissez une étape ou explorez le schéma du flux.</p></div></div><div class="scroll-track" aria-hidden="true"><span></span></div></div></section><section class="application-cta section"><div>${eyebrow('LE BON MODÈLE POUR VOTRE INSTALLATION')}<h2>Votre procédé<br>a ses particularités.</h2></div><div><p>Fluide, pression, débit et contraintes d’installation : ces éléments permettent de préparer le dimensionnement.</p><p class="small-note">Les performances doivent être confirmées pour l’application retenue. La maquette ne réalise aucun calcul de dimensionnement.</p>${primary('Définir mon besoin','data-need="Dropout — air comprimé"')}</div></section>`}
