import { state, draft } from '../state.js';
import { escapeHTML } from '../lib/dom.js';
import { FAMILIES } from '../data/families.js';
import { primary } from '../ui/button.js';

/* Parcours « definir mon besoin » : trois etapes, aucune donnee transmise. */
export function familyOptions(){return ['Dropout — air comprimé',...FAMILIES.map(f=>f.name),'Autre / à préciser'].map(v=>`<option ${draft.family===v?'selected':''}>${v}</option>`).join('')}

export function summary(compact=false){const data=[['Besoin',draft.family],['Application',draft.application||'À préciser'],['Pression',draft.unknown?'À définir':draft.pressure?draft.pressure+' bar':'Non renseignée'],['Débit',draft.unknown?'À définir':draft.flow?draft.flow+' m³/h':'Non renseigné']];if(!compact)data.push(['Contact',draft.name],['Entreprise',draft.company||'Non renseignée'],['E-mail',draft.email]);return `<dl class="summary">${data.map(([k,v])=>`<div><dt>${k}</dt><dd>${escapeHTML(v)}</dd></div>`).join('')}</dl>`}

export function fields(){
  const done = state.done;
  const step = state.step;
  if(done)return `<div class="form-success" role="status"><span class="success-mark" aria-hidden="true">✓</span><span class="mono">DÉMONSTRATION TERMINÉE</span><h2>Le premier pas<br>est fait.</h2><p>Votre parcours est terminé. Aucune demande n’a été envoyée à Maturat.</p><p class="small-note">Recommencez avec une nouvelle application pour explorer un autre besoin.</p>${primary('Recommencer','type="button" data-reset')}</div>`;
if(step===0)return `<span class="mono form-kicker">01 / VOTRE BESOIN</span><h2>Parlons de votre application.</h2><p class="form-intro">Quelques mots suffisent pour commencer.</p><label for="family">Votre besoin</label><select name="family" id="family">${familyOptions()}</select><label for="application">Que souhaitez-vous mesurer ou protéger ? <span>*</span></label><textarea id="application" name="application" required maxlength="1800" placeholder="Ex. : protéger les instruments de notre réseau d’air comprimé…">${escapeHTML(draft.application)}</textarea><fieldset><legend>Paramètres connus <span>(facultatif)</span></legend><div class="parameter-fields"><div><label for="pressure">Pression</label><div class="unit-input"><input id="pressure" name="pressure" type="number" inputmode="decimal" min="0" step="any" value="${escapeHTML(draft.pressure)}" ${draft.unknown?'disabled':''} placeholder="7"><span>bar</span></div></div><div><label for="flow">Débit</label><div class="unit-input"><input id="flow" name="flow" type="number" inputmode="decimal" min="0" step="any" value="${escapeHTML(draft.flow)}" ${draft.unknown?'disabled':''} placeholder="À préciser"><span>m³/h</span></div></div></div><label class="check"><input type="checkbox" name="unknown" ${draft.unknown?'checked':''}>Je ne connais pas encore ces valeurs</label></fieldset><div class="form-actions"><span class="small-note">* Champ requis</span>${primary('Continuer','type="submit"')}</div>`;
if(step===1)return `<span class="mono form-kicker">02 / VOTRE CONTACT</span><h2>Faisons connaissance.</h2><p class="form-intro">Utilisez des coordonnées fictives pour tester ce parcours.</p><label for="name">Prénom et nom <span>*</span></label><input id="name" name="name" required maxlength="120" autocomplete="name" value="${escapeHTML(draft.name)}" placeholder="Camille Martin"><label for="company">Entreprise <span>(facultatif)</span></label><input id="company" name="company" maxlength="150" autocomplete="organization" value="${escapeHTML(draft.company)}" placeholder="Votre entreprise"><label for="email">Adresse e-mail professionnelle <span>*</span></label><input id="email" name="email" type="email" required maxlength="200" autocomplete="email" value="${escapeHTML(draft.email)}" placeholder="camille@example.com"><div class="form-actions"><button type="button" data-prev>← Retour</button>${primary('Vérifier la demande','type="submit"')}</div>`;
return `<span class="mono form-kicker">03 / VOTRE RÉSUMÉ</span><h2>Votre demande, en clair.</h2>${summary()}<p class="small-note">Cette démonstration ne transmet aucune information à Maturat.</p><div class="form-actions"><button type="button" data-prev>← Modifier</button>${primary('Simuler la demande','type="submit"')}</div>`}
